<a href="https://colab.research.google.com/github/mabitha-7/mlops_training/blob/main/LR_FOR_NOWN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/factory_worker_safety_multimodal_dataset_v2.csv")
df.head()

,Report_ID,Image_Path,Video_Path,Audio_Path,PPE_Status,Body_Posture,Zone_Violation,Workers_Visible,PPE_Compliance_Score,Image_Confidence,...,Fall_Detected,Video_Frame_Rate,Video_Confidence,Incident_Description,Incident_Type,Text_Sentiment,Urgency_Level,Text_Word_Count,Fusion_Risk_Score,Risk_Level
0,R0001,images/img_0001.jpg,videos/video_0001.mp4,audio/audio_0001.wav,No Helmet,Standing,No,2,0.27,0.91,...,No,30,0.87,Worker collapsed near heavy machinery zone,Worker Fall,Critical,Critical,6,0.637,High
1,R0002,images/img_0002.jpg,videos/video_0002.mp4,audio/audio_0002.wav,Improper PPE,Running,Yes,4,0.51,0.93,...,No,24,0.81,Machine guard removed for manual cleaning with...,Machine Hazard,Neutral,High,8,0.537,High
2,R0003,images/img_0003.jpg,videos/video_0003.mp4,audio/audio_0003.wav,Improper PPE,Fallen,Yes,4,0.50,0.98,...,Yes,24,0.90,Combustible material stored improperly near ma...,Fire Hazard,Critical,High,6,0.593,Moderate
3,R0004,images/img_0004.jpg,videos/video_0004.mp4,audio/audio_0004.wav,No Mask,Fallen,Yes,2,0.44,0.81,...,Yes,30,0.89,Chemical spill reported in sector B production...,Chemical Leak,Critical,High,8,0.611,High
4,R0005,images/img_0005.jpg,videos/video_0005.mp4,audio/audio_0005.wav,No Mask,Crouching,No,4,0.38,0.97,...,No,25,0.78,Unauthorized personnel detected in high voltag...,Restricted Area Entry,Critical,High,7,0.704,High

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Report_ID               1500 non-null   object
 1   Image_Path              1500 non-null   object
 2   Video_Path              1500 non-null   object
 3   Audio_Path              1500 non-null   object
 4   PPE_Status              1500 non-null   object
 5   Body_Posture            1500 non-null   object
 6   Zone_Violation          1500 non-null   object
 7   Workers_Visible         1500 non-null   int64
 8   PPE_Compliance_Score    1500 non-null   float64
 9   Image_Confidence        1500 non-null   float64
 10  Audio_Event             1500 non-null   object
 11  Audio_dB_Level          1500 non-null   float64
 12  Audio_Dominant_Freq_Hz  1500 non-null   float64
 13  Audio_Duration_Sec      1500 non-null   float64
 14  Audio_Confidence        1500 non-null   float64
 15  Activity_Detected       1500 non-null   object
 16  Motion_Intensity        1500 non-null   object
 17  Fall_Detected           1500 non-null   object
 18  Video_Frame_Rate        1500 non-null   int64
 19  Video_Confidence        1500 non-null   float64
 20  Incident_Description    1500 non-null   object
 21  Incident_Type           1500 non-null   object
 22  Text_Sentiment          1500 non-null   object
 23  Urgency_Level           1500 non-null   object
 24  Text_Word_Count         1500 non-null   int64
 25  Fusion_Risk_Score       1500 non-null   float64
 26  Risk_Level              1500 non-null   object
dtypes: float64(8), int64(3), object(16)
memory usage: 316.5+ KB

In [5]:
df.columns

Index(['Report_ID', 'Image_Path', 'Video_Path', 'Audio_Path', 'PPE_Status',
       'Body_Posture', 'Zone_Violation', 'Workers_Visible',
       'PPE_Compliance_Score', 'Image_Confidence', 'Audio_Event',
       'Audio_dB_Level', 'Audio_Dominant_Freq_Hz', 'Audio_Duration_Sec',
       'Audio_Confidence', 'Activity_Detected', 'Motion_Intensity',
       'Fall_Detected', 'Video_Frame_Rate', 'Video_Confidence',
       'Incident_Description', 'Incident_Type', 'Text_Sentiment',
       'Urgency_Level', 'Text_Word_Count', 'Fusion_Risk_Score', 'Risk_Level'],
      dtype='object')

In [7]:
df.shape

(1500, 27)

In [8]:
df.isnull().sum()

Report_ID                 0
Image_Path                0
Video_Path                0
Audio_Path                0
PPE_Status                0
Body_Posture              0
Zone_Violation            0
Workers_Visible           0
PPE_Compliance_Score      0
Image_Confidence          0
Audio_Event               0
Audio_dB_Level            0
Audio_Dominant_Freq_Hz    0
Audio_Duration_Sec        0
Audio_Confidence          0
Activity_Detected         0
Motion_Intensity          0
Fall_Detected             0
Video_Frame_Rate          0
Video_Confidence          0
Incident_Description      0
Incident_Type             0
Text_Sentiment            0
Urgency_Level             0
Text_Word_Count           0
Fusion_Risk_Score         0
Risk_Level                0
dtype: int64

In [13]:
x= df[['PPE_Compliance_Score','Audio_dB_Level','Audio_Confidence','Video_Confidence','Text_Word_Count']]

In [10]:
y = df['Fusion_Risk_Score']

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
from sklearn.linear_model import LinearRegression
m=LinearRegression()

In [21]:
m.fit(x_train,y_train)

LinearRegression()

In [23]:
yp=m.predict(x_test)

In [25]:
yp[:5]

array([0.62330003, 0.57592478, 0.40139727, 0.57241535, 0.55984504])

In [26]:
y_test[:5]

1116    0.824
1368    0.707
422     0.630
413     0.582
451     0.475
Name: Fusion_Risk_Score, dtype: float64

In [27]:
s=m.score(x_test,y_test)
s

0.20784060650643965

In [28]:
from sklearn.metrics import mean_squared_error

In [30]:
mse = mean_squared_error(y_test, yp)
mse

0.01777093877137893

In [32]:
m.coef_

array([-2.92203902e-01, -1.41394824e-04,  3.66350858e-02,  3.09826035e-02,
        4.04207052e-03])

In [33]:
m.intercept_

np.float64(0.620762729611139)

In [34]:
import joblib

In [35]:
joblib.dump(m,"LINEARREG_OWN.pkl")

['LINEARREG_OWN.pkl']