<a href="https://colab.research.google.com/github/mabitha-7/mlops_training/blob/main/TASK_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv("/content/factory_worker_safety_multimodal_dataset_v2.csv")

In [4]:
df.head()

,Report_ID,Image_Path,Video_Path,Audio_Path,PPE_Status,Body_Posture,Zone_Violation,Workers_Visible,PPE_Compliance_Score,Image_Confidence,...,Fall_Detected,Video_Frame_Rate,Video_Confidence,Incident_Description,Incident_Type,Text_Sentiment,Urgency_Level,Text_Word_Count,Fusion_Risk_Score,Risk_Level
0,R0001,images/img_0001.jpg,videos/video_0001.mp4,audio/audio_0001.wav,No Helmet,Standing,No,2,0.27,0.91,...,No,30,0.87,Worker collapsed near heavy machinery zone,Worker Fall,Critical,Critical,6,0.637,High
1,R0002,images/img_0002.jpg,videos/video_0002.mp4,audio/audio_0002.wav,Improper PPE,Running,Yes,4,0.51,0.93,...,No,24,0.81,Machine guard removed for manual cleaning with...,Machine Hazard,Neutral,High,8,0.537,High
2,R0003,images/img_0003.jpg,videos/video_0003.mp4,audio/audio_0003.wav,Improper PPE,Fallen,Yes,4,0.50,0.98,...,Yes,24,0.90,Combustible material stored improperly near ma...,Fire Hazard,Critical,High,6,0.593,Moderate
3,R0004,images/img_0004.jpg,videos/video_0004.mp4,audio/audio_0004.wav,No Mask,Fallen,Yes,2,0.44,0.81,...,Yes,30,0.89,Chemical spill reported in sector B production...,Chemical Leak,Critical,High,8,0.611,High
4,R0005,images/img_0005.jpg,videos/video_0005.mp4,audio/audio_0005.wav,No Mask,Crouching,No,4,0.38,0.97,...,No,25,0.78,Unauthorized personnel detected in high voltag...,Restricted Area Entry,Critical,High,7,0.704,High

In [6]:
df.shape

(1500, 27)

In [8]:
df.columns

Index(['Report_ID', 'Image_Path', 'Video_Path', 'Audio_Path', 'PPE_Status',
       'Body_Posture', 'Zone_Violation', 'Workers_Visible',
       'PPE_Compliance_Score', 'Image_Confidence', 'Audio_Event',
       'Audio_dB_Level', 'Audio_Dominant_Freq_Hz', 'Audio_Duration_Sec',
       'Audio_Confidence', 'Activity_Detected', 'Motion_Intensity',
       'Fall_Detected', 'Video_Frame_Rate', 'Video_Confidence',
       'Incident_Description', 'Incident_Type', 'Text_Sentiment',
       'Urgency_Level', 'Text_Word_Count', 'Fusion_Risk_Score', 'Risk_Level'],
      dtype='object')

In [9]:
df.isnull().sum()

Report_ID                 0
Image_Path                0
Video_Path                0
Audio_Path                0
PPE_Status                0
Body_Posture              0
Zone_Violation            0
Workers_Visible           0
PPE_Compliance_Score      0
Image_Confidence          0
Audio_Event               0
Audio_dB_Level            0
Audio_Dominant_Freq_Hz    0
Audio_Duration_Sec        0
Audio_Confidence          0
Activity_Detected         0
Motion_Intensity          0
Fall_Detected             0
Video_Frame_Rate          0
Video_Confidence          0
Incident_Description      0
Incident_Type             0
Text_Sentiment            0
Urgency_Level             0
Text_Word_Count           0
Fusion_Risk_Score         0
Risk_Level                0
dtype: int64

In [10]:
df = df.drop(['Report_ID','Image_Path','Video_Path','Audio_Path','Incident_Description'], axis=1)

In [11]:
df=df.dropna()

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [14]:
for col in df.columns:
  if df[col].dtype=='object':
    df[col]=le.fit_transform(df[col])

In [15]:
x=df.drop("Risk_Level",axis=1)

In [16]:
y=df["Risk_Level"]

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
from sklearn.ensemble import RandomForestClassifier
m=RandomForestClassifier(n_estimators=100,random_state=42)

In [21]:
m.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [22]:
yp=m.predict(x_test)

In [23]:
from sklearn.metrics import accuracy_score, classification_report
a=accuracy_score(y_test,yp)
a

0.8466666666666667

In [24]:
classification_report(y_test,yp)

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

'              precision    recall  f1-score   support\n\n           0       0.91      0.90      0.91       125\n           1       0.94      0.42      0.58        38\n           2       0.79      0.92      0.85       136\n           3       0.00      0.00      0.00         1\n\n    accuracy                           0.85       300\n   macro avg       0.66      0.56      0.58       300\nweighted avg       0.86      0.85      0.84       300\n'

In [25]:
import joblib
joblib.dump(m,"Workersaftey.pkl")

['Workersaftey.pkl']

In [26]:
s=x.iloc[0:1]
p=m.predict(s)
p

array([0])

In [27]:
pl=le.inverse_transform(p)
pl

array(['High'], dtype=object)